version: '3'

services:
  swimlanes:
    build: .
    networks:
      - caddy
    labels:
      caddy: swimlanes.motoroco.co
      caddy.reverse_proxy: "{{upstreams 3000}}"
    restart: unless-stopped

networks:
  caddy:
    external: true
